name: shrine
description: Learn how to use Material for structure and layout.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  cupertino_icons: ^1.0.3
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  provider: ^6.0.1
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.1.0
  image_picker: ^0.8.4+1
  path_provider: ^2.0.4
  firebase_storage: ^10.1.0
  youtube_player_flutter: ^8.0.0
  flutter_speed_dial: ^3.0.5
  document_scanner_flutter: ^0.2.5
  advance_pdf_viewer: ^2.0.0
  html_editor_enhanced: ^2.4.0+1
  flutter_html: ^2.1.2
  flutter_pdfview: ^1.2.1
  flutter_svg: ^0.22.0
  google_maps_flutter: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true